
[input]

[input.gelf]
url = "0.0.0.0:19999"


[output]

[output.elas]
batch_secs = 10
type = "elasticsearch"
batch_max = 500
index = "k8s-dev"

[output.stdout]
type = "stdout"

[route]

[route.es]
input = "gelf"
output = "elas"
if_has_field = "pd_log"

[route.stdout]
input = "gelf"
output = "stdout"
#if_has_field = "pd_event"
