
[input]

[input.gelf]
url = "localhost:5555"


[output]

[output.elas]
host = "localhost"
batch_secs = 20
type = "elasticsearch"
batch_max = 500
index = "k8s-dev"


[output.pg]
type = "postgres"
batch_directory = "./tmp"
batch_secs = 300
retry_secs = 30
buffer_max = 1000000
json_schema = "./schema.json"

[route]

[route.default]
input = "gelf"
output = "pg"

[rout.to_es]
input = "gelf"
output = "elas"
