
[input]

[input.gelf]
url = "localhost:5555"


[output]

[output.s3]
batch_secs = 20
type = "s3"
batch_max = 20000
batch_directory = "."
bucket = "dev.service.events"

[route]

[route.default]
input = "gelf"
output = "s3"

